const famousPeople = [
  'Albert Einstein',
  'Isaac Newton',
  'Nikola Tesla',
  'Leonardo da Vinci',
  'Marie Curie',
  'Galileo Galilei',
  'Charles Darwin',
  'Stephen Hawking',
  'Alan Turing',
  'Ada Lovelace',
  'Aristotle',
  'Plato',
  'Socrates',
  'Confucius',
  'Laozi',
  'Shakespeare',
  'Homer',
  'Dante Alighieri',
  'Jane Austen',
  'Mark Twain',
  'Mozart',
  'Beethoven',
  'Bach',
  'Tchaikovsky',
  'Chopin',
  'Abraham Lincoln',
  'George Washington',
  'Napoleon Bonaparte',
  'Julius Caesar',
  'Winston Churchill',
  'Barack Obama',
  'Donald Trump',
  'Theodore Roosevelt',
  'John F. Kennedy',
  'Franklin D. Roosevelt',
  'Elon Musk',
  'Steve Jobs',
  'Bill Gates',
  'Jeff Bezos',
  'Mark Zuckerberg',
  'Oprah Winfrey',
  'Walt Disney',
  'Coco Chanel',
  'J.K. Rowling',
  'Stephen King',
  'Muhammad Ali',
  'Michael Jordan',
  'Kobe Bryant',
  'Cristiano Ronaldo',
  'Lionel Messi',
  'Usain Bolt',
  'Serena Williams',
  'Roger Federer',
  'Tiger Woods',
  'Pele',
  'Bruce Lee',
  'Jackie Chan',
  'Arnold Schwarzenegger',
  'Dwayne Johnson',
  'Sylvester Stallone',
  'Angelina Jolie',
  'Tom Cruise',
  'Leonardo DiCaprio',
  'Meryl Streep',
  'Johnny Depp',
  'Marilyn Monroe',
  'Audrey Hepburn',
  'Charlie Chaplin',
  'Alfred Hitchcock',
  'Quentin Tarantino',
  'Genghis Khan',
  'Alexander the Great',
  'Cleopatra',
  'Joan of Arc',
  'Queen Victoria',
  'Dalai Lama',
  'Pope Francis',
  'Mother Teresa',
  'Mahatma Gandhi',
  'Nelson Mandela',
  'Vincent van Gogh',
  'Pablo Picasso',
  'Claude Monet',
  'Salvador Dalí',
  'Frida Kahlo',
  'Isaac Asimov',
  'Carl Sagan',
  'Richard Feynman',
  'Neil deGrasse Tyson',
  'Brian Cox',
  'Martin Luther King Jr.',
  'Malcolm X',
  'Che Guevara',
  'Vladimir Lenin',
  'Joseph Stalin',
]

export function getRandomPairs(): [string, string] {
  const shuffled = [...famousPeople].sort(() => Math.random() - 0.5)
  return [shuffled[0], shuffled[3]]
}
