import type { Metadata } from 'next'
import { Inter, Orbitron } from 'next/font/google'
import './globals.css'
import { Suspense } from 'react'
import { AuthContextProvider } from '@/contexts/AuthContext'
import useUserServer from '@/hooks/useUserServer'
import { Toaster } from 'sonner'
import { Footer } from '@/components/Footer'
import { Navbar } from '@/components/Navbar'

const orbitron = Orbitron({
  variable: '--font-orbitron',
  subsets: ['latin'],
})

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const user = await useUserServer()

  return (
    <html lang="en">
      <body
        className={`${orbitron.variable} ${inter.variable} font-inter  overflow-x-hidden  antialiased`}
      >
        <Suspense>
          <AuthContextProvider user={user}>
            <Navbar />
            <main className="w-full min-h-screen flex flex-col  bg-gray-900 text-blue-100 overflow-hidden">
              {children}
            </main>
            <Toaster />

            <Footer />
          </AuthContextProvider>
        </Suspense>{' '}
      </body>
    </html>
  )
}
